const modes = [
  { slug: 'apl', name: 'APL' },
  { slug: 'asn.1', name: 'ASN.1' },
  { slug: 'asterisk', name: 'Asterisk dialplan' },
  { slug: 'brainfuck', name: 'Brainfuck' },
  {
    slug: 'clike',
    name: 'C, C++, C#, Ceylon, Java, Kotlin, Objective C, Scala, Squirrel',
  },
  { slug: 'clojure', name: 'Clojure' },
  { slug: 'css', name: 'Closure Stylesheets (GSS), CSS, LESS, SCSS' },
  { slug: 'cmake', name: 'CMake' },
  { slug: 'cobol', name: 'COBOL' },
  { slug: 'coffeescript', name: 'CoffeeScript' },
  { slug: 'commonlisp', name: 'Common Lisp' },
  { slug: 'crystal', name: 'Crystal' },
  { slug: 'cypher', name: 'Cypher' },
  { slug: 'python', name: 'Cython, Python' },
  { slug: 'd', name: 'D' },
  { slug: 'dart', name: 'Dart' },
  { slug: 'django', name: 'Django' },
  { slug: 'dockerfile', name: 'Dockerfile' },
  { slug: 'diff', name: 'diff' },
  { slug: 'dtd', name: 'DTD' },
  { slug: 'dylan', name: 'Dylan' },
  { slug: 'ebnf', name: 'EBNF' },
  { slug: 'ecl', name: 'ECL' },
  { slug: 'eiffel', name: 'Eiffel' },
  { slug: 'elm', name: 'Elm' },
  { slug: 'erlang', name: 'Erlang' },
  { slug: 'factor', name: 'Factor' },
  { slug: 'fcl', name: 'FCL' },
  { slug: 'forth', name: 'Forth' },
  { slug: 'fortran', name: 'Fortran' },
  { slug: 'mllike', name: 'F#, OCaml' },
  { slug: 'gas', name: 'Gas' },
  { slug: 'gherkin', name: 'Gherkin' },
  { slug: 'go', name: 'Go' },
  { slug: 'groovy', name: 'Groovy' },
  { slug: 'haml', name: 'HAML' },
  { slug: 'handlebars', name: 'Handlebars' },
  { slug: 'haskell', name: 'Haskell' },
  { slug: 'haskell-literate', name: 'Literate' },
  { slug: 'haxe', name: 'Haxe' },
  { slug: 'htmlembedded', name: 'HTML embedded' },
  { slug: 'htmlmixed', name: 'HTML mixed-mode' },
  { slug: 'http', name: 'HTTP' },
  { slug: 'idl', name: 'IDL' },
  { slug: 'javascript', name: 'JavaScript' },
  { slug: 'jsx', name: 'JSX' },
  { slug: 'jinja2', name: 'Jinja2' },
  { slug: 'julia', name: 'Julia' },
  { slug: 'livescript', name: 'LiveScript' },
  { slug: 'lua', name: 'Lua' },
  { slug: 'markdown', name: 'Markdown' },
  { slug: 'gfm', name: 'GitHub-flavour' },
  { slug: 'mathematica', name: 'Mathematica' },
  { slug: 'mbox', name: 'mbox' },
  { slug: 'mirc', name: 'mIRC' },
  { slug: 'modelica', name: 'Modelica' },
  { slug: 'mscgen', name: 'MscGen' },
  { slug: 'mumps', name: 'MUMPS' },
  { slug: 'nginx', name: 'Nginx' },
  { slug: 'nsis', name: 'NSIS' },
  { slug: 'ntriples', name: 'N-Triples/N-Quads' },
  { slug: 'octave', name: 'Octave' },
  { slug: 'oz', name: 'Oz' },
  { slug: 'pascal', name: 'Pascal' },
  { slug: 'pegjs', name: 'PEG.js' },
  { slug: 'perl', name: 'Perl' },
  { slug: 'asciiarmor', name: 'PGP (ASCII armor)' },
  { slug: 'php', name: 'PHP' },
  { slug: 'pig', name: 'Pig Latin' },
  { slug: 'powershell', name: 'PowerShell' },
  { slug: 'properties', name: 'Properties files' },
  { slug: 'protobuf', name: 'ProtoBuf' },
  { slug: 'pug', name: 'Pug' },
  { slug: 'puppet', name: 'Puppet' },
  { slug: 'q', name: 'Q' },
  { slug: 'r', name: 'R' },
  { slug: 'rpm', name: 'RPM' },
  { slug: 'rst', name: 'reStructuredText' },
  { slug: 'ruby', name: 'Ruby' },
  { slug: 'rust', name: 'Rust' },
  { slug: 'sas', name: 'SAS' },
  { slug: 'sass', name: 'Sass' },
  { slug: 'spreadsheet', name: 'Spreadsheet' },
  { slug: 'scheme', name: 'Scheme' },
  { slug: 'shell', name: 'Shell' },
  { slug: 'sieve', name: 'Sieve' },
  { slug: 'slim', name: 'Slim' },
  { slug: 'smalltalk', name: 'Smalltalk' },
  { slug: 'smarty', name: 'Smarty' },
  { slug: 'solr', name: 'Solr' },
  { slug: 'soy', name: 'Soy' },
  { slug: 'stylus', name: 'Stylus' },
  { slug: 'sql', name: 'SQL' },
  { slug: 'sparql', name: 'SPARQL' },
  { slug: 'swift', name: 'Swift' },
  { slug: 'stex', name: 'sTeX, LaTeX' },
  { slug: 'tcl', name: 'Tcl' },
  { slug: 'textile', name: 'Textile' },
  { slug: 'tiddlywiki', name: 'Tiddlywiki' },
  { slug: 'tiki', name: 'Tiki wiki' },
  { slug: 'toml', name: 'TOML' },
  { slug: 'tornado', name: 'Tornado' },
  { slug: 'troff', name: 'troff' },
  { slug: 'ttcn', name: 'TTCN' },
  { slug: 'ttcn-cfg', name: 'TTCN Configuration' },
  { slug: 'turtle', name: 'Turtle' },
  { slug: 'twig', name: 'Twig' },
  { slug: 'vb', name: 'VB.NET' },
  { slug: 'vbscript', name: 'VBScript' },
  { slug: 'velocity', name: 'Velocity' },
  { slug: 'verilog', name: 'Verilog/SystemVerilog' },
  { slug: 'vhdl', name: 'VHDL' },
  { slug: 'vue', name: 'Vue.js app' },
  { slug: 'webidl', name: 'Web IDL' },
  { slug: 'wast', name: 'WebAssembly Text Format' },
  { slug: 'xml', name: 'XML/HTML' },
  { slug: 'xquery', name: 'XQuery' },
  { slug: 'yacas', name: 'Yacas' },
  { slug: 'yaml', name: 'YAML' },
  { slug: 'yaml-frontmatter', name: 'YAML frontmatter' },
  { slug: 'z80', name: 'Z80' },
]

export default modes
